### ISSUE TITLE
Makefile doesn't define a PREFIX

### ISSUE THREAD

**Issue by ZLLentz** [pcdshub/lcls-plc-lfe-gem#7]
this is causing some problems with standard PVs

https://github.com/pcdshub/lcls-plc-lfe-gem/blob/bebfab532c0e1c811f4b1e757a280bbda109b7f1/iocBoot/ioc-plc-lfe-gem/Makefile#L12

**Comment by klauer** [comment]
This should be resolved soon - it can create problems with other misconfigured IOCs and doesn't allow us to look at this PLC's status through the normal channels.
